Alpha18 vuex aggregation
n-multimedia/nm_stream pull request #17
Opened 2021-02-19 11:14 UTC by n-multimedia

2021-02-19 14:11 UTC, null requested changes
Uffala. paar anmerkungen...

2021-02-21 19:44 UTC, n-multimedia commented on src/assets/config.js
> +        apiInitAgrUrl: 'http://localhost:9501/api/v2.0/nm_stream/initialize_aggregated',
gut gesehen :D

2021-02-21 19:44 UTC, n-multimedia commented on src/components/views/StreamPost.vue
> +        console.log(response)
kommt weg

2021-02-21 19:45 UTC, n-multimedia commented on src/components/widgets/StreamFilter.vue
> +      return !!(this.contextSearch && (!this.contextSelected || this.contextSearch != this.contextSelected.title))
hier an der stelle gewachsen und vermutlich unnötig aber nicht schädlich: 
https://www.samanthaming.com/tidbits/19-2-ways-to-convert-to-boolean/

2021-02-21 19:47 UTC, n-multimedia commented on src/store/index.js
> +    mutations: {
ohja nix geht mehr ohne :D

2021-02-22 09:43 UTC, null approved these changes
ich glaub dann sollts passen

2021-02-22 09:43 UTC, merged